// 预设小说模板种子数据
exports.seed = async function (knex) {
  // 先清空已有数据
  await knex('novel_templates').del();

  await knex('novel_templates').insert([
    {
      name: 'xianxia_standard',
      display_name: '标准修仙',
      description: '凡人逆袭、步步登仙的经典修仙模板，包含完整的境界体系和宗门设定，适合长篇连载',
      category: '玄幻',
      cover_gradient: 'linear-gradient(135deg, #0c0c2d 0%, #1a1a5e 40%, #6b3fa0 100%)',
      icon: 'ThunderboltOutlined',
      genre: '玄幻',
      title_example: '凡人仙途',
      theme: '逆境中坚守本心，在力量与道心之间寻找平衡。探讨长生与凡人情感的冲突，问道与入世的抉择。',
      setting: '九州大地，灵气充沛，万族林立。修炼体系分为：炼气、筑基、金丹、元婴、化神、合体、大乘、渡劫八大境界。每个境界又分初期、中期、后期、圆满四个小境界。天下宗门以"一殿二宗三谷四派"为尊，另有散修联盟、商会、炼丹师公会等势力。',
      main_plot: '主角出身微末，偶得上古大能遗物/传承，踏上修炼之路。修炼途中遭遇宗门争斗、秘境探险、正魔大战。中期发现自身身世隐秘，牵涉到上古布局。后期对抗域外天魔/幕后黑手，最终证道飞升。',
      is_official: true,
      sort_order: 1,
    },
    {
      name: 'urban_romance',
      display_name: '都市甜宠',
      description: '现代都市背景的浪漫爱情故事，突出甜蜜互动与成长蜕变，适合女性向创作',
      category: '都市',
      cover_gradient: 'linear-gradient(135deg, #f093fb 0%, #f5576c 50%, #fda085 100%)',
      icon: 'HeartOutlined',
      genre: '都市',
      title_example: '总裁的契约新娘',
      theme: '爱是相互成就而非占有。在现实压力与情感冲动之间，每个人都需要找到属于自己的答案。',
      setting: '现代都市，繁华的滨海城市。故事主要围绕商业精英、娱乐圈、豪门世家展开。经济发达，社会阶层分明。',
      main_plot: '女主因意外与高冷总裁产生交集，被迫签订契约婚姻/恋爱协议。相处过程中逐渐发现彼此的真实一面。经历情敌挑衅、家族反对、商业阴谋等考验后，两人克服障碍，收获真爱。',
      is_official: true,
      sort_order: 2,
    },
    {
      name: 'sci_fi_interstellar',
      display_name: '星际科幻',
      description: '未来星际文明背景下的史诗冒险，融合机甲、基因进化、外星文明等经典科幻元素',
      category: '科幻',
      cover_gradient: 'linear-gradient(135deg, #0c2b4f 0%, #1b5e8a 40%, #00d4aa 100%)',
      icon: 'RocketOutlined',
      genre: '科幻',
      title_example: '星海征途',
      theme: '技术与人性的边界在哪里？当人类进入星际时代，古老的道德困境以新的形式呈现。探索未知不仅是征服星辰大海，更是对自我的认知。',
      setting: '公元3587年，人类已建立横跨银河系的庞大星际联邦。科技以量子引擎、基因强化、AI意识上传为核心。机甲战士是战场主力，精神力觉醒者成为特殊战略资源。外星种族有虫族、灵族、硅基生命等。',
      main_plot: '主角从偏远星球出发，意外发现远古文明遗迹，获得超越当前时代的科技/能力。被各方势力追逐的过程中，卷入星际联邦与虫族的全面战争。逐步揭开远古文明灭绝的真相，最终推动人类文明进入新纪元。',
      is_official: true,
      sort_order: 3,
    },
    {
      name: 'suspense_investigation',
      display_name: '悬疑推理',
      description: '环环相扣的案件推理模板，从微末线索中抽丝剥茧，揭开惊天真相',
      category: '悬疑',
      cover_gradient: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)',
      icon: 'SearchOutlined',
      genre: '悬疑',
      title_example: '暗夜追踪',
      theme: '真相往往藏于细节之中。正义的实现不在于惩罚，而在于还原每一个受害者的故事。',
      setting: '现代都市背景下，围绕刑侦队、法医中心、犯罪心理学研究室展开。案件涉及连环犯罪、高科技作案、跨国组织等。',
      main_plot: '一桩看似普通的案件，牵扯出多年前的悬案。主角凭借敏锐的观察力和缜密的推理，发现案件之间的隐秘关联。在查案过程中，自身也被卷入更大的阴谋，必须在限时内找到真相。',
      is_official: true,
      sort_order: 4,
    },
    {
      name: 'game_vrmmorpg',
      display_name: '虚拟网游',
      description: '全息虚拟现实游戏世界，从新手村到巅峰玩家的成长之路，游戏与现实的交织',
      category: '游戏',
      cover_gradient: 'linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)',
      icon: 'AppleOutlined',
      genre: '游戏',
      title_example: '第二世界',
      theme: '虚拟世界的价值如何衡量？当游戏装备可以改变现实命运，游戏不再是单纯的娱乐。在规则与漏洞之间，每个玩家都在书写自己的传奇。',
      setting: '2045年，全球最大虚拟现实MMORPG《永恒大陆》上线。玩家通过意识接入舱进入100%拟真度的游戏世界。游戏经济与现实货币互通，职业玩家和公会体系成熟。',
      main_plot: '主角因现实困境进入游戏，凭借前世的游戏记忆/特殊天赋，在新手村获得隐藏职业/装备。一步步建立自己的公会势力，参与游戏内的史诗级事件。随着游戏深入，发现游戏世界隐藏的秘密可能关乎人类文明的未来。',
      is_official: true,
      sort_order: 5,
    },
    {
      name: 'light_novel_campus',
      display_name: '校园轻小说',
      description: '轻松愉快的校园日常+超自然元素，适合轻快节奏的青春故事创作',
      category: '轻小说',
      cover_gradient: 'linear-gradient(135deg, #a8edea 0%, #fed6e3 50%, #d4a5ff 100%)',
      icon: 'SmileOutlined',
      genre: '轻小说',
      title_example: '我与超能力者的日常',
      theme: '青春最珍贵的不是超能力，而是身边愿意陪你犯傻的朋友。日常的点滴构成了最不平凡的回忆。',
      setting: '明德中学，一所有着百年历史的名校。校园内隐藏着不为人知的秘密——部分学生觉醒了超能力。学生会在暗中维护校园的日常秩序，防止超能力事件影响普通学生的生活。',
      main_plot: '转学第一天，主角意外卷入超能力者之间的争斗。阴差阳错加入学生会"特殊事务处理部"，在日常校园生活与超自然事件之间来回奔波。结识各具特色的同伴，一起解决校园内发生的各种奇异事件。',
      is_official: true,
      sort_order: 6,
    },
    {
      name: 'history_alternate',
      display_name: '架空历史',
      description: '穿越/重生到历史背景的平行世界，利用现代知识成就一番事业',
      category: '历史',
      cover_gradient: 'linear-gradient(135deg, #3c2a21 0%, #6b4226 40%, #c9a96e 100%)',
      icon: 'ReadOutlined',
      genre: '历史',
      title_example: '大梁风华',
      theme: '历史的车轮下，个人的选择能否改变命运？在已有的知识框架中，如何平衡预知与顺其自然。',
      setting: '大梁王朝，国力正处于由盛转衰的关键节点。科举制度完备，商业发达但受到官僚压制。周边有北戎、南蛮、东夷等势力，海疆有倭寇侵扰。',
      main_plot: '现代人意外穿越/重生为大梁王朝的一个小人物（书生/商人/庶子），凭借对历史的了解和现代管理知识，从地方开始逐步积累实力。通过科举入仕/经营商业/治军练兵等途径崛起，在王朝危机中力挽狂澜。',
      is_official: true,
      sort_order: 7,
    },
    {
      name: 'blank_custom',
      display_name: '空白模板',
      description: '完全空白的起点，仅包含基础的创作指引，让您从零自由发挥想象力',
      category: '其他',
      cover_gradient: 'linear-gradient(135deg, #2d3748 0%, #4a5568 100%)',
      icon: 'EditOutlined',
      genre: null,
      title_example: null,
      theme: null,
      setting: null,
      main_plot: null,
      is_official: true,
      sort_order: 99,
    },
  ]);
};
